#!/bin/bash

echo "🔍 Checking Frontend Environment Configuration..."
echo ""
echo "📂 Environment Files:"
echo "├── .env.production:"
cat frontend/.env.production 2>/dev/null || echo "   ❌ Not found"
echo ""
echo "├── .env.local:"
cat frontend/.env.local 2>/dev/null || echo "   ❌ Not found"
echo ""
echo "├── .env:"
cat frontend/.env 2>/dev/null || echo "   ❌ Not found"
echo ""
echo "📋 Vercel Configuration:"
cat frontend/vercel.json 2>/dev/null || echo "❌ vercel.json not found"
echo ""
echo "🔧 To manually test the API URL in production:"
echo "1. Open browser console on https://verdan-beige.vercel.app/"
echo "2. Look for logs starting with 🔗 API Base URL"
echo "3. Should show: https://verdan-787l.vercel.app/"
echo ""
echo "🚀 If still showing localhost, run: npm run build && npm run preview"
echo "   to test the production build locally"